#!/bin/bash

cat <<-EOF

Vous pouvez lancer tout module dont vous avez precise le nom
Tapez <return> pour installer les modules, puis encore <return> pour les arreter
EOF

read junk
sudo insmod /usr/realtime/modules/rtai_hal.ko
sudo insmod /usr/realtime/modules/rtai_sched.ko
sudo insmod /usr/realtime/modules/rtai_sem.ko
sudo insmod /usr/realtime/modules/rtai_fifos.ko
sudo insmod 3712.ko
sudo insmod module_Entree.ko
sudo insmod module_Sortie.ko
sudo insmod module_TestES.ko

lsmod
echo "Le programme fontionne :o"
echo "Tapez <return> pour l'arreter."
read junk

sudo rmmod module_TestES
sudo rmmod module_Sortie
sudo rmmod module_Entree
sudo rmmod 3712
sudo rmmod rtai_fifos
sudo rmmod rtai_sem
sudo rmmod rtai_sched
sudo rmmod rtai_hal
